### ISSUE TITLE
detect_chords function

### ISSUE THREAD

**Issue by caseywescott** [cienicera/midi_fun_contract#17]
**Objective:**
Implement a chord detection function within the MidiTrait to analyze MIDI note events and identify chords.

Return a Midi of extracted chords.

**Rough Spec:**

**Inputs:**
self: A reference to a Midi object containing note events.
window_size (usize): The number of MIDI ticks to group events for chord analysis.
minimum_notes (usize): The minimum number of simultaneous notes required to consider it a chord.

**Output:** A Midi representing detected chords.

**Contains:**
Time: The time at which the chord occurs.
Chord Notes 

**Behavior:**
Traverse MIDI events within the provided Midi object.
Group NOTE_ON events within the specified window_size into simultaneous note clusters.
For each group:
Extract the pitch classes of active notes.
Identify whether the group meets the minimum_notes threshold.
If valid, append the chord to the result.
Return a list of chords detected along with their respective timestamps.

**Comment by ikemHood** [comment]
Can I jump on this task?
I have experience writing cairo contracts

**Comment by ikemHood** [comment]
💫
