### ISSUE TITLE
octave_doubling function

### ISSUE THREAD

**Issue by caseywescott** [cienicera/midi_fun_contract#18]
**Octave Doubling**

Add an additional note one or more octaves higher or lower.

fn octave_double(self: @Midi, octave_count: i32) -> Midi;

**Inputs:**
self: A reference to a Midi object containing note events.
octave_count (i32): The number of octaves to double the notes (positive for higher octaves, negative for lower).

**Outputs:**
Result: A Midi object with octave-doubled notes added.
Behavior:
Traverse the Midi events.
Identify all NOTE_ON and NOTE_OFF events.
For each event:
Duplicate the event with its pitch adjusted by 12 * octave_count.
Ensure the pitch stays within the MIDI note range (0–127).
Preserve timing, velocity, and other properties of the original event.
Append the octave-doubled events to the Midi object.

**Implementation Notes**
Use MIDI pitch constraints (0–127) to filter invalid notes after transposition.
Leverage PitchClassTrait for pitch manipulations.
Ensure that all non-note events (SET_TEMPO, CONTROL_CHANGE, etc.) remain unchanged.
Implement error handling for invalid channel inputs when apply_to_all_channels is false.

**Comment by NueloSE** [comment]
Would love to tackle this!
