### ISSUE TITLE
invert_notes function

### ISSUE THREAD

**Issue by caseywescott** [cienicera/midi_fun_contract#19]
**Inputs:**
self: A reference to a Midi object containing note events.
pivot_note (u8): The MIDI note number (0–127) around which inversion occurs.

**Outputs:**
Result: A Midi object with inverted notes.

**Behavior:**
Traverse the Midi events.
Identify all NOTE_ON and NOTE_OFF events.
For each note:
Calculate the inverted pitch around the specified pivot_note using the formula:
inverted_pitch = pivot_note + (pivot_note - original_pitch)
Ensure the pitch stays within the MIDI note range (0–127).
Preserve timing, velocity, and other properties of the original note.
Replace original notes with their inverted counterparts.

**Implementation Notes**
Use MIDI pitch constraints (0–127) to filter invalid notes after inversion.
Leverage PitchClassTrait for pitch manipulations.
Ensure all non-note events (SET_TEMPO, CONTROL_CHANGE, etc.) remain unchanged.
Implement error handling for invalid channel inputs when apply_to_all_channels is false.

**Comment by vestor-dev** [comment]
hey @caseywescott can i have this issue
