### ISSUE TITLE
Implement Param Args and Control Flow for music() 

### ISSUE THREAD

**Issue by caseywescott** [cienicera/midi_fun_contract#4]
Overview: This task involves integrating the advanced musical computations native to the KOJI library enabling contract function music() to take arguments to that modulate the musical output

1. Add Arguments and Logic in music() for KOJI Computations
Details:
* Implement logic for the following musical operations using the KOJI library:
    * transpose_notes: Shift pitch of notes by a specified interval.
    * quantize_notes: Align notes to a predefined timing grid.
    * change_note_duration: Adjust the length of notes.
    * change_tempo: Modify the playback speed of the composition.
    * remap_instruments: Change instrument mappings.
    * generate_harmony: Add harmonization to existing notes.
Deliverables:
* Update the music() function.
* Ensure smooth integration of KOJI computations.

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to lots of other projects. I would love to work on this.

**Comment by petersdt** [comment]
Could I grab this task?

**Comment by Supa-mega** [comment]
can i please be assigned this issues

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue
